// <auto-generated> myFSM class generator — do not edit by hand.
// Module: MazeRunner (v0.5, 2 states).
// Self-contained: attach this component and press Play - the module it
// runs is compiled in at the bottom of this file. Nothing to assign.
using UnityEngine;
using MyFSM.Unity;

public sealed partial class MazeRunnerAI : AIInstance
{
    protected override string GeneratedModuleName
    {
        get { return "MazeRunner"; }
    }

    public const string State_Run = "Run";
    public const string State_Done = "Done";

    public const int Slot_self = 0; // Object3D
    public const int Slot_exit = 1; // Object3D
    public const int Slot_plannedLength = 2; // float
    public const int Slot_arrived = 3; // bool

    // Runtime-variable overrides: the base auto-binds every UNIQUE
    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,
    // Transform2D/3D -> transform, component types -> GetComponent).
    // Edits here are lost on recompile - durable overrides belong in a
    // hand-written partial file implementing OnBindingsManual().
    protected override void OnBindingsRequired()
    {
        base.OnBindingsRequired();
        // Slot_self (Object3D): AMBIGUOUS (2x) - Bind(Slot_self, /* GameObject/Component */);
        // Slot_exit (Object3D): AMBIGUOUS (2x) - Bind(Slot_exit, /* GameObject/Component */);
        // Slot_plannedLength (float): value - SetBoundValue(Slot_plannedLength, FsmValue.MakeFloat(0f));
        // Slot_arrived (bool): value - SetBoundValue(Slot_arrived, FsmValue.MakeBool(false));
        OnBindingsManual();
    }

    partial void OnBindingsManual();

    // ================================================================
    // THIS AI'S BRAIN - 475 bytes of compiled module.
    // It is the .fsmb, base64-encoded so it can live in a C# file. The
    // base class reads it; nothing here needs assigning or editing.
    // ================================================================
    private static readonly byte[] ModuleData =
        System.Convert.FromBase64String(
            "RE1TRgAABQAkAAAAJAAAAGwAAABsAAAAgwAAALsAAADDAQAAAAAAQCEAAAAABABzZWxmDwAAQCEBAAAABABleGl0HgAAQAIC" +
            "AAAADQBwbGFubmVkTGVuZ3RoNgAAQAQDAAAABwBhcnJpdmVkAgAAAAAAAMADAFJ1bsYAAMAEAERvbmUEAACABAACAh4AAEAt" +
            "AADAAQFnAADAAwENAACAAwEEAACADQAAgAIAAQHkAADAAgI2AABAAAEAwAECAAwAAMCGAADAAQICABcAAMCDAADABwIAIgAA" +
            "wGcAAMATAAAeAABALQAAwBAAAAMGATcAAMAQAAAABgJFAADAVgAAwBAAAAABAU8AAMAjAAAAAABAEAAAAAEBYAAAwCMAAA8A" +
            "AEAQAAAXBgJ1AADAfAAAwCMAAAAAAEAjAAAPAABACAAAAwIAkQAAwL8AAMAEAQC4AADAnAAAwBAAAAcGAqoAAMCxAADAIwAA" +
            "AAAAQCMAAA8AAEARAAANAACAEQAABAAAgAEBAM4AAMAAAgIA2QAAwAUBAMAHAgDkAADA9QAAwBAAACsGAe4AAMAjAAAAAABA" +
            "EwAANgAAQAABAMAiAAAEAQgAAAIAAAAEAACAAgANAACABAAAgA0AAIAAAA=="
        );
    protected override byte[] EmbeddedModule
    {
        get { return ModuleData; }
    }
}
