// <auto-generated> myFSM class generator — do not edit by hand.
// Module: testai (v0.5, 1 states).
// Self-contained: attach this component and press Play - the module it
// runs is compiled in at the bottom of this file. Nothing to assign.
using UnityEngine;
using MyFSM.Unity;

public sealed partial class TestAI : AIInstance
{
    protected override string GeneratedModuleName
    {
        get { return "testai"; }
    }

    public const string State_Chase = "Chase";

    public const int Slot_agent = 0; // NavMeshAgent
    public const int Slot_dest = 1; // Object3D
    public const int Slot_speed = 2; // float

    // Runtime-variable overrides: the base auto-binds every UNIQUE
    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,
    // Transform2D/3D -> transform, component types -> GetComponent).
    // Edits here are lost on recompile - durable overrides belong in a
    // hand-written partial file implementing OnBindingsManual().
    protected override void OnBindingsRequired()
    {
        base.OnBindingsRequired();
        // Slot_agent (NavMeshAgent): auto-bound (unique type) - override with Bind(Slot_agent, ...) if needed.
        // Slot_dest (Object3D): auto-bound (unique type) - override with Bind(Slot_dest, ...) if needed.
        // Slot_speed (float): value - SetBoundValue(Slot_speed, FsmValue.MakeFloat(0f));
        OnBindingsManual();
    }

    partial void OnBindingsManual();

    // ================================================================
    // THIS AI'S BRAIN - 188 bytes of compiled module.
    // It is the .fsmb, base64-encoded so it can live in a C# file. The
    // base class reads it; nothing here needs assigning or editing.
    // ================================================================
    private static readonly byte[] ModuleData =
        System.Convert.FromBase64String(
            "RE1TRgAABQAkAAAAJAAAAFMAAABTAAAAYgAAAG4AAACyAAAAAAAAQHAAAAAABQBhZ2VudBAAAEAhAQAAAAQAZGVzdB8AAEAC" +
            "AgAAAAUAc3BlZWQBAAAAAAAAwAUAQ2hhc2UEAACAAQABAR0AAMABAQAIAADAAQICABMAAMAWAADABwAACAEAHQAAwBAAACUG" +
            "Ay8AAMA2AADAPQAAwCMAAAAAAEAjAAAQAABAIwAAHwAAQAEAAAAEAACAAAA="
        );
    protected override byte[] EmbeddedModule
    {
        get { return ModuleData; }
    }
}
