// <auto-generated> myFSM class generator — do not edit by hand.
// Module: Guard (v0.5, 2 states).
// Self-contained: attach this component and press Play - the module it
// runs is compiled in at the bottom of this file. Nothing to assign.
using UnityEngine;
using MyFSM.Unity;

public sealed partial class GuardAI : AIInstance
{
    protected override string GeneratedModuleName
    {
        get { return "Guard"; }
    }

    public const string State_Guard = "Guard";
    public const string State_Deregistered = "Deregistered";

    public const int Slot_intruder = 0; // Object3D
    public const int Slot_guard = 1; // Object3D
    public const int Slot_guardAnim = 2; // AnimationController3D
    public const int Slot_guardLight = 3; // Sprite3D
    public const int Slot_shotEventId = 4; // int

    // Runtime-variable overrides: the base auto-binds every UNIQUE
    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,
    // Transform2D/3D -> transform, component types -> GetComponent).
    // Edits here are lost on recompile - durable overrides belong in a
    // hand-written partial file implementing OnBindingsManual().
    protected override void OnBindingsRequired()
    {
        base.OnBindingsRequired();
        // Slot_intruder (Object3D): AMBIGUOUS (2x) - Bind(Slot_intruder, /* GameObject/Component */);
        // Slot_guard (Object3D): AMBIGUOUS (2x) - Bind(Slot_guard, /* GameObject/Component */);
        // Slot_guardAnim (AnimationController3D): auto-bound (unique type) - override with Bind(Slot_guardAnim, ...) if needed.
        // Slot_guardLight (Sprite3D): auto-bound (unique type) - override with Bind(Slot_guardLight, ...) if needed.
        // Slot_shotEventId (int): value - SetBoundValue(Slot_shotEventId, FsmValue.MakeInt(0));
        OnBindingsManual();
    }

    partial void OnBindingsManual();

    // ================================================================
    // THIS AI'S BRAIN - 1181 bytes of compiled module.
    // It is the .fsmb, base64-encoded so it can live in a C# file. The
    // base class reads it; nothing here needs assigning or editing.
    // ================================================================
    private static readonly byte[] ModuleData =
        System.Convert.FromBase64String(
        "RE1TRgAABQAkAAAAOAAAAJoAAADDAAAA5AAAAIABAAB9BAAAAAAAIAIAACBBCQBmaXJlUmFuZ2UAAABAIQAAAAAIAGludHJ1" +
        "ZGVyEwAAQCEBAAAABQBndWFyZCMAAEBRAgAAAAkAZ3VhcmRBbmltNwAAQEEDAAAACgBndWFyZExpZ2h0TAAAQAEEAAAACwBz" +
        "aG90RXZlbnRJZAAAAGAECQB3YXNGaXJpbmcQAABgAgQAZGlzdBsAAGAEBwBjYW5GaXJlAgAAAAAAAMAFAEd1YXJkeAIAwAwA" +
        "RGVyZWdpc3RlcmVkBAAAgBAAAgIAAABgJwAAwAICEAAAYFoAAMACAhsAAGCJAADAAQHWAADAAQHnAADAAQEyAQDAAQFOAQDA" +
        "AQFfAQDAAQF5AQDAAgIAAABgoQEAwAEB5wEAwAEBAwIAwAICAAAAYB8CAMACAgAAAGA2AgDAAwEPAACAAwEEAACADwAAgAQA" +
        "AQGaAgDAAQGrAgDAAwEEAACAAwEPAACAAQQAFAAAwBwAAMAsAADAOwIAwAESAAAEAAAAYBMAAAAAAGAnAADAIgAABAACBgBH" +
        "AADATwAAwHYAAMB+AADAywAAwAEBAMASAAACEAAAYBMAABAAAGBaAADAEAAACAcCaAAAwG8AAMAjAAATAABAIwAAAAAAQBIA" +
        "AAQbAABgEwAAGwAAYIkAAMAgAAAHlQAAwLEAAMAQAAACBwKjAADAqgAAwCMAABMAAEAjAAAAAABAIAAADr0AAMDEAADAIwAA" +
        "EAAAYCMAAAAAACAHAgDWAADA5wAAwBAAAAADAeAAAMAjAAAjAABAEAAABgIC9QAAwPwAAMAjAAA3AABAIgAABAAIAwAQAQDA" +
        "pgEAwCQCAMAEBQAyAQDATgEAwF8BAMB5AQDAlgEAwCsBAMAjAAAbAABgEAAAAAcCQAEAwEcBAMAjAAATAABAIwAAAAAAQBAA" +
        "AAIKAVgBAMAjAABMAABAEAAABgICbQEAwHQBAMAjAAA3AABAIgAABAEQAAAQAwKHAQDAjgEAwCMAACMAAEAiAAABAQAAABMA" +
        "AAAAAGChAQDAIgAABAEFAwDnAQDAAwIAwBQCAMC5AQDAIAAADsUBAMDMAQDAIwAAEAAAYCAAAAPYAQDA3wEAwCMAAAAAACAi" +
        "AAACAAAAQBAAAAAHAvUBAMD8AQDAIwAAEwAAQCMAAAAAAEAQAAAAAwENAgDAIwAAIwAAQBMAAAAAAGAfAgDAIgAABAAGAQAr" +
        "AgDAEwAAAAAAYDYCAMAiAAAEAAMCAEYCAMBxAgDABAEAagIAwFECAMAhAAAJWQIAwBAAAA4BAWMCAMAjAAAAAABAEQAADwAA" +
        "gBEAAAQAAIABAgCEAgDAyAIAwAACAgCPAgDAxQIAwAcCAJoCAMCrAgDAEAAAAgMBpAIAwCMAACMAAEAQAAAGAgK5AgDAwAIA" +
        "wCMAADcAAEAiAAAEAAgAAAMCANMCAMD2AgDABAEA7wIAwN4CAMAQAAAOAQHoAgDAIwAAAAAAQBEAAAQAAIARAAAPAACAAgAA" +
        "AAQAAIACAA8AAIAEAACADwAAgAIABAAAgA8AAIA="
    );
    protected override byte[] EmbeddedModule
    {
        get { return ModuleData; }
    }
}
