// <auto-generated> myFSM class generator — do not edit by hand.
// Module: Patrol (v0.5, 4 states).
using UnityEngine;
using MyFSM.Unity;

public sealed partial class PatrolAI : AIInstance
{
    public const string AssetResourcePath = "MyFSM/Patrol";
    protected override string ModuleResourcePath
    {
        get { return AssetResourcePath; }
    }
    protected override string GeneratedModuleName
    {
        get { return "Patrol"; }
    }

    public const string State_GoToA = "GoToA";
    public const string State_PauseAtA = "PauseAtA";
    public const string State_GoToB = "GoToB";
    public const string State_PauseAtB = "PauseAtB";

    public const int Slot_agent = 0; // NavMeshAgent
    public const int Slot_waypointA = 1; // Object3D
    public const int Slot_waypointB = 2; // Object3D

    // Runtime-variable overrides: the base auto-binds every UNIQUE
    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,
    // Transform2D/3D -> transform, component types -> GetComponent).
    // Edits here are lost on recompile - durable overrides belong in a
    // hand-written partial file implementing OnBindingsManual().
    protected override void OnBindingsRequired()
    {
        base.OnBindingsRequired();
        // Slot_agent (NavMeshAgent): auto-bound (unique type) - override with Bind(Slot_agent, ...) if needed.
        // Slot_waypointA (Object3D): AMBIGUOUS (2x) - Bind(Slot_waypointA, /* GameObject/Component */);
        // Slot_waypointB (Object3D): AMBIGUOUS (2x) - Bind(Slot_waypointB, /* GameObject/Component */);
        OnBindingsManual();
    }

    partial void OnBindingsManual();
}
