// <auto-generated> myFSM class generator — do not edit by hand.
// Module: patrol (v0.5, 4 states).
// Self-contained: attach this component and press Play - the module it
// runs is compiled in at the bottom of this file. Nothing to assign.
using UnityEngine;
using MyFSM.Unity;

public sealed partial class PatrolAI : AIInstance
{
    protected override string GeneratedModuleName
    {
        get { return "patrol"; }
    }

    public const string State_GoToA = "GoToA";
    public const string State_PauseAtA = "PauseAtA";
    public const string State_GoToB = "GoToB";
    public const string State_PauseAtB = "PauseAtB";

    public const int Slot_agent = 0; // NavMeshAgent
    public const int Slot_waypointA = 1; // Object3D
    public const int Slot_waypointB = 2; // Object3D

    // Runtime-variable overrides: the base auto-binds every UNIQUE
    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,
    // Transform2D/3D -> transform, component types -> GetComponent).
    // Edits here are lost on recompile - durable overrides belong in a
    // hand-written partial file implementing OnBindingsManual().
    protected override void OnBindingsRequired()
    {
        base.OnBindingsRequired();
        // Slot_agent (NavMeshAgent): auto-bound (unique type) - override with Bind(Slot_agent, ...) if needed.
        // Slot_waypointA (Object3D): AMBIGUOUS (2x) - Bind(Slot_waypointA, /* GameObject/Component */);
        // Slot_waypointB (Object3D): AMBIGUOUS (2x) - Bind(Slot_waypointB, /* GameObject/Component */);
        OnBindingsManual();
    }

    partial void OnBindingsManual();

    // ================================================================
    // THIS AI'S BRAIN - 1039 bytes of compiled module.
    // It is the .fsmb, base64-encoded so it can live in a C# file. The
    // base class reads it; nothing here needs assigning or editing.
    // ================================================================
    private static readonly byte[] ModuleData =
        System.Convert.FromBase64String(
            "RE1TRgAABQAkAAAAOQAAAHEAAACJAAAAvwAAAEcBAADTAwAAAAAAIAEDAAAACgBwYXVzZVRpY2tzAAAAQHAAAAAABQBhZ2Vu" +
            "dBAAAEAhAQAAAAkAd2F5cG9pbnRBJAAAQCECAAAACQB3YXlwb2ludEIAAABgAQUAdGlja3MMAABgAQUAdGlja3MEAAAAAAAA" +
            "wAUAR29Ub0GJAADACABQYXVzZUF0QUYBAMAFAEdvVG9CzwEAwAgAUGF1c2VBdEIEAACAAwABAR4AAMADAQ8AAIADAQQAAIAP" +
            "AACABQACAgAAAGCwAADAAQHKAADAAgIAAABg7QAAwAMBHQAAgAMBDwAAgB0AAIADAAEBZAEAwAMBKAAAgAMBHQAAgCgAAIAF" +
            "AAICDAAAYPYBAMABARACAMACAgwAAGAzAgDAAwEEAACAAwEoAACAAQIADAAAwEkAAMABAgIAFwAAwEYAAMAHAQAeAADAEAAA" +
            "JQYDMAAAwDcAAMA+AADAIwAAAAAAQCMAABAAAEAiAAACAABgQAgAAAMCAFQAAMCCAADABAEAewAAwF8AAMAQAAAFBgJtAADA" +
            "dAAAwCMAAAAAAEAjAAAQAABAEQAADwAAgBEAAAQAAIABBACdAADApQAAwLgAAMAIAQDAABIAAAEAAABgEwAAAAAAYLAAAMAi" +
            "AAABAAAAAAICAMMAAMDbAADABwEAygAAwBAAACoGAdQAAMAjAAAAAABACAEA4gAAwBMAAAAAAGDtAADAIAAAAfkAAMAAAQDA" +
            "IwAAAAAAYCIAAAEBAAAAAwIAEwEAwD8BAMAEAQA4AQDAHgEAwCAAAA8qAQDAMQEAwCMAAAAAAGAjAAAAAAAgEQAAHQAAgBEA" +
            "AA8AAIABAgBSAQDAjwEAwAACAgBdAQDAjAEAwAcBAGQBAMAQAAAlBgN2AQDAfQEAwIQBAMAjAAAAAABAIwAAJAAAQCIAAAIA" +
            "AGBACAAAAwIAmgEAwMgBAMAEAQDBAQDApQEAwBAAAAUGArMBAMC6AQDAIwAAAAAAQCMAACQAAEARAAAoAACAEQAAHQAAgAEE" +
            "AOMBAMDrAQDA/gEAwE4CAMAAEgAAAQwAAGATAAAMAABg9gEAwCIAAAEAAAAAAgIACQIAwCECAMAHAQAQAgDAEAAAKgYBGgIA" +
            "wCMAAAAAAEAIAQAoAgDAEwAADAAAYDMCAMAgAAABPwIAwEYCAMAjAAAMAABgIgAAAQEAAAADAgBZAgDAhQIAwAQBAH4CAMBk" +
            "AgDAIAAAD3ACAMB3AgDAIwAADAAAYCMAAAAAACARAAAEAACAEQAAKAAAgAQAAAAEAACAAgAPAACABAAAgA8AAIACAB0AAIAP" +
            "AACAHQAAgAIAKAAAgB0AAIAoAACAAgAEAACAKAAAgA=="
        );
    protected override byte[] EmbeddedModule
    {
        get { return ModuleData; }
    }
}
