// <auto-generated> myFSM class generator — do not edit by hand.
// Module: Patrol (v0.5, 4 states).
// NOTE: the commented OnBindingsRequired example at the end was added by
// hand; everything above it is byte-identical generator output.
using UnityEngine;
using MyFSM.Unity;

public sealed class PatrolAI : AIInstance
{
    public const string AssetResourcePath = "MyFSM/Patrol";
    protected override string ModuleResourcePath
    {
        get { return AssetResourcePath; }
    }
    protected override string GeneratedModuleName
    {
        get { return "Patrol"; }
    }

    public const string State_GoToA = "GoToA";
    public const string State_PauseAtA = "PauseAtA";
    public const string State_GoToB = "GoToB";
    public const string State_PauseAtB = "PauseAtB";

    public const int Slot_agent = 0; // NavMeshAgent
    public const int Slot_waypointA = 1; // Object3D
    public const int Slot_waypointB = 2; // Object3D

    // Example: bind scene objects in code instead of (or besides) the
    // inspector list. Runs after the inspector bindings, before boot.
    // Uncomment and adapt to your scene:
    //
    // protected override void OnBindingsRequired()
    // {
    //     Bind(Slot_agent, GameObject.Find("PatrolBot").GetComponent<UnityEngine.AI.NavMeshAgent>());
    //     Bind(Slot_waypointA, GameObject.Find("WaypointA"));
    //     Bind(Slot_waypointB, GameObject.Find("WaypointB"));
    // }
}
