// <auto-generated> myFSM class generator — do not edit by hand.
// Module: PathChaser (v0.5, 2 states).
// Self-contained: attach this component and press Play - the module it
// runs is compiled in at the bottom of this file. Nothing to assign.
using UnityEngine;
using MyFSM.Unity;

public sealed partial class PathChaserAI : AIInstance
{
    protected override string GeneratedModuleName
    {
        get { return "PathChaser"; }
    }

    public const string State_Chase = "Chase";
    public const string State_Caught = "Caught";

    public const int Slot_self = 0; // Object3D
    public const int Slot_target = 1; // Object3D
    public const int Slot_plannedLength = 2; // float
    public const int Slot_caught = 3; // bool

    // Runtime-variable overrides: the base auto-binds every UNIQUE
    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,
    // Transform2D/3D -> transform, component types -> GetComponent).
    // Edits here are lost on recompile - durable overrides belong in a
    // hand-written partial file implementing OnBindingsManual().
    protected override void OnBindingsRequired()
    {
        base.OnBindingsRequired();
        // Slot_self (Object3D): AMBIGUOUS (2x) - Bind(Slot_self, /* GameObject/Component */);
        // Slot_target (Object3D): AMBIGUOUS (2x) - Bind(Slot_target, /* GameObject/Component */);
        // Slot_plannedLength (float): value - SetBoundValue(Slot_plannedLength, FsmValue.MakeFloat(0f));
        // Slot_caught (bool): value - SetBoundValue(Slot_caught, FsmValue.MakeBool(false));
        OnBindingsManual();
    }

    partial void OnBindingsManual();

    // ================================================================
    // THIS AI'S BRAIN - 513 bytes of compiled module.
    // It is the .fsmb, base64-encoded so it can live in a C# file. The
    // base class reads it; nothing here needs assigning or editing.
    // ================================================================
    private static readonly byte[] ModuleData =
        System.Convert.FromBase64String(
            "RE1TRgAABQAkAAAAOgAAAIMAAACDAAAAngAAANYAAADpAQAAAAAAIAIAAABACwBjYXRjaFJhZGl1cwAAAEAhAAAAAAQAc2Vs" +
            "Zg8AAEAhAQAAAAYAdGFyZ2V0IAAAQAICAAAADQBwbGFubmVkTGVuZ3RoOAAAQAQDAAAABgBjYXVnaHQCAAAAAAAAwAUAQ2hh" +
            "c2XRAADABgBDYXVnaHQEAACABAACAiAAAEAwAADAAQFqAADAAwEPAACAAwEEAACADwAAgAIAAQHvAADAAgI4AABACwEAwAEC" +
            "AAwAAMCGAADAAQICABcAAMAaAADABwAACAIAJQAAwGoAAMATAAAgAABAMAAAwBAAAAMGAToAAMAQAAAABgJIAADAWQAAwBAA" +
            "AAABAVIAAMAjAAAAAABAEAAAAAEBYwAAwCMAAA8AAEAQAAAXBgJ4AADAfwAAwCMAAAAAAEAjAAAPAABAAwIAkQAAwMoAAMAE" +
            "AQDDAADAnAAAwBAAAAQHA64AAMC1AADAvAAAwCMAAAAAAEAjAAAPAABAIwAAAAAAIBEAAA8AAIARAAAEAACAAQEA2QAAwAAC" +
            "AgDkAADAEAEAwAcCAO8AAMAAAQDAEAAAKwYB+QAAwCMAAAAAAEATAAA4AABACwEAwCIAAAQBCAAAAgAAAAQAAIACAA8AAIAE" +
            "AACADwAAgAAA"
        );
    protected override byte[] EmbeddedModule
    {
        get { return ModuleData; }
    }
}
