// myFSM Unity Runtime — .fsmb -> C# class generator (editor-time contract).
//
// Produces the source of a named PARTIAL class inheriting AIInstance for one
// module: one generated class <=> one AI. The generator is plain string
// building (no UnityEditor dependency): run it from an editor menu/script,
// save the .cs, done. Besides pinning the module's Resources path it emits
// state-name and binding-slot constants so game code never hardcodes strings
// or slot ints, plus an OnBindingsRequired override: per-slot comments mark
// auto-bound (unique-type) vs AMBIGUOUS (shared-type, bind manually) vs
// value slots, and a partial OnBindingsManual() hook gives hand-written
// partial files a durable override point (inline edits are lost on
// recompile; the partial file is never rewritten).

using System;
using System.Collections.Generic;
using System.Text;
using MyFSM.Core;

namespace MyFSM.Unity
{
    public static class ClassGenerator
    {
        private static readonly HashSet<string> Keywords = new HashSet<string>()
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
            "char", "checked", "class", "const", "continue", "decimal",
            "default", "delegate", "do", "double", "else", "enum", "event",
            "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface",
            "internal", "is", "lock", "long", "namespace", "new", "null",
            "object", "operator", "out", "override", "params", "private",
            "protected", "public", "readonly", "ref", "return", "sbyte",
            "sealed", "short", "sizeof", "stackalloc", "static", "string",
            "struct", "switch", "this", "throw", "true", "try", "typeof",
            "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
            "virtual", "void", "volatile", "while"
        };

        public static string SanitizeIdentifier(string raw)
        {
            if (string.IsNullOrEmpty(raw)) return "_";
            StringBuilder sb = new StringBuilder(raw.Length + 1);
            for (int i = 0; i < raw.Length; i++)
            {
                char ch = raw[i];
                bool ok = (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                          ch == '_' || (ch >= '0' && ch <= '9' && i > 0);
                sb.Append(ok ? ch : '_');
            }
            if (sb.Length > 0 && sb[0] >= '0' && sb[0] <= '9')
                sb.Insert(0, '_');
            string ident = sb.ToString();
            if (Keywords.Contains(ident)) ident = "@" + ident;
            return ident;
        }

        // FsmValue maker call (without the "FsmValue." prefix) rendering a
        // zero example for a value-type name; used in slot comments only.
        private static string MakerForValueType(string typeName)
        {
            switch (typeName)
            {
                case "int": return "MakeInt(0)";
                case "float": return "MakeFloat(0f)";
                case "double": return "MakeDouble(0.0)";
                case "bool": return "MakeBool(false)";
                case "string": return "MakeString(\"\")";
                case "Vector2": return "MakeVec2(0f, 0f)";
                case "Vector3": return "MakeVec3(0f, 0f, 0f)";
                case "Quaternion": return "MakeQuat(0f, 0f, 0f, 1f)";
                default: return "/* see FsmValue makers */";
            }
        }

        /// <summary>
        /// Builds the full .cs source for a module. moduleName is the asset
        /// stem (e.g. "Patrol"), className the desired class (e.g. "PatrolAI"),
        /// resourcePath the Resources path of the .fsmb (e.g. "MyFSM/Patrol").
        /// Pass the compiled module bytes to embed them in the class so the
        /// generated script needs no .fsmb asset at runtime.
        /// </summary>
        public static string GenerateSource(FsmbModule module, string moduleName,
                                            string className, string resourcePath)
        {
            return GenerateSource(module, null, moduleName, className, resourcePath);
        }

        /// <summary>
        /// Same, with the raw module bytes: they are emitted as a base64 blob
        /// plus an EmbeddedModule override, so the generated class IS the AI -
        /// no .fsmb asset, no Resources folder, nothing to assign.
        /// </summary>
        public static string GenerateSource(FsmbModule module, byte[] moduleBytes,
                                            string moduleName, string className,
                                            string resourcePath)
        {
            string cls = SanitizeIdentifier(className);
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> myFSM class generator — do not edit by hand.");
            bool embed = moduleBytes != null && moduleBytes.Length > 0;
            sb.AppendLine("// Module: " + moduleName + " (v" + module.Major + "." +
                          module.Minor + ", " + module.States.Count + " states).");
            if (embed)
                sb.AppendLine("// Self-contained: attach this component and press Play - the module it");
            if (embed)
                sb.AppendLine("// runs is compiled in at the bottom of this file. Nothing to assign.");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using MyFSM.Unity;");
            sb.AppendLine();
            sb.AppendLine("public sealed partial class " + cls + " : AIInstance");
            sb.AppendLine("{");
            if (!embed)
            {
                // Legacy shape: no bytes to carry, so the class can only point
                // at a Resources asset. Regenerating with the burst compiler
                // replaces this with a self-contained class.
                sb.AppendLine("    public const string AssetResourcePath = \"" + resourcePath + "\";");
                sb.AppendLine("    protected override string ModuleResourcePath");
                sb.AppendLine("    {");
                sb.AppendLine("        get { return AssetResourcePath; }");
                sb.AppendLine("    }");
            }
            sb.AppendLine("    protected override string GeneratedModuleName");
            sb.AppendLine("    {");
            sb.AppendLine("        get { return \"" + moduleName + "\"; }");
            sb.AppendLine("    }");
            sb.AppendLine();
            for (int i = 0; i < module.States.Count; i++)
            {
                sb.AppendLine("    public const string State_" +
                              SanitizeIdentifier(module.States[i].Name) + " = \"" +
                              module.States[i].Name + "\";");
            }
            if (module.Runtime.Count > 0) sb.AppendLine();
            for (int i = 0; i < module.Runtime.Count; i++)
            {
                sb.AppendLine("    public const int Slot_" +
                              SanitizeIdentifier(module.Runtime[i].Name) + " = " +
                              module.Runtime[i].BindingSlot + "; // " +
                              DslTypes.NameOf(module.Runtime[i].Tag));
            }
            sb.AppendLine();
            sb.AppendLine("    // Runtime-variable overrides: the base auto-binds every UNIQUE");
            sb.AppendLine("    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,");
            sb.AppendLine("    // Transform2D/3D -> transform, component types -> GetComponent).");
            sb.AppendLine("    // Edits here are lost on recompile - durable overrides belong in a");
            sb.AppendLine("    // hand-written partial file implementing OnBindingsManual().");
            sb.AppendLine("    protected override void OnBindingsRequired()");
            sb.AppendLine("    {");
            sb.AppendLine("        base.OnBindingsRequired();");
            Dictionary<byte, int> perTag = new Dictionary<byte, int>();
            for (int i = 0; i < module.Runtime.Count; i++)
            {
                byte tag = module.Runtime[i].Tag;
                int n;
                perTag.TryGetValue(tag, out n);
                perTag[tag] = n + 1;
            }
            for (int i = 0; i < module.Runtime.Count; i++)
            {
                string slotConst = "Slot_" + SanitizeIdentifier(module.Runtime[i].Name);
                byte tag = module.Runtime[i].Tag;
                DslTypeInfo info;
                bool known = DslTypes.TryFindByTag(tag, out info);
                string typeName = known ? info.Name : "tag 0x" + tag.ToString("X2");
                if (known && info.IsHandle && perTag[tag] == 1)
                {
                    sb.AppendLine("        // " + slotConst + " (" + typeName +
                        "): auto-bound (unique type) - override with Bind(" +
                        slotConst + ", ...) if needed.");
                }
                else if (known && info.IsHandle)
                {
                    sb.AppendLine("        // " + slotConst + " (" + typeName +
                        "): AMBIGUOUS (" + perTag[tag] + "x) - Bind(" + slotConst +
                        ", /* GameObject/Component */);");
                }
                else if (known)
                {
                    sb.AppendLine("        // " + slotConst + " (" + typeName +
                        "): value - SetBoundValue(" + slotConst + ", FsmValue." +
                        MakerForValueType(typeName) + ");");
                }
                else
                {
                    sb.AppendLine("        // " + slotConst + " (" + typeName +
                        "): unknown type - bind manually.");
                }
            }
            sb.AppendLine("        OnBindingsManual();");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    partial void OnBindingsManual();");
            if (embed)
            {
                // Kept at the very bottom, out of the way of the part a human
                // reads. It is not decoration: this is the compiled module, and
                // the class is only self-contained because it is here.
                string b64 = Convert.ToBase64String(moduleBytes);
                sb.AppendLine();
                sb.AppendLine("    // ================================================================");
                sb.AppendLine("    // THIS AI'S BRAIN - " + moduleBytes.Length + " bytes of compiled module.");
                sb.AppendLine("    // It is the .fsmb, base64-encoded so it can live in a C# file. The");
                sb.AppendLine("    // base class reads it; nothing here needs assigning or editing.");
                sb.AppendLine("    // ================================================================");
                sb.AppendLine("    private static readonly byte[] ModuleData =");
                sb.AppendLine("        System.Convert.FromBase64String(");
                for (int i = 0; i < b64.Length; i += 96)
                {
                    int len = Math.Min(96, b64.Length - i);
                    string line = "            \"" + b64.Substring(i, len) + "\"";
                    if (i + len < b64.Length) line += " +";
                    sb.AppendLine(line);
                }
                sb.AppendLine("        );");
                sb.AppendLine("    protected override byte[] EmbeddedModule");
                sb.AppendLine("    {");
                sb.AppendLine("        get { return ModuleData; }");
                sb.AppendLine("    }");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
