// myFSM Unity Runtime — .fsmb -> C# class generator (editor-time contract).
//
// Produces the source of a named class inheriting AIInstance for one module:
// one generated class <=> one AI. The generator is plain string building (no
// UnityEditor dependency): run it from an editor menu/script, save the .cs,
// done. Besides pinning the module's Resources path it emits state-name and
// binding-slot constants so game code never hardcodes strings or slot ints.

using System;
using System.Collections.Generic;
using System.Text;
using MyFSM.Core;

namespace MyFSM.Unity
{
    public static class ClassGenerator
    {
        private static readonly HashSet<string> Keywords = new HashSet<string>()
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
            "char", "checked", "class", "const", "continue", "decimal",
            "default", "delegate", "do", "double", "else", "enum", "event",
            "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface",
            "internal", "is", "lock", "long", "namespace", "new", "null",
            "object", "operator", "out", "override", "params", "private",
            "protected", "public", "readonly", "ref", "return", "sbyte",
            "sealed", "short", "sizeof", "stackalloc", "static", "string",
            "struct", "switch", "this", "throw", "true", "try", "typeof",
            "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
            "virtual", "void", "volatile", "while"
        };

        public static string SanitizeIdentifier(string raw)
        {
            if (string.IsNullOrEmpty(raw)) return "_";
            StringBuilder sb = new StringBuilder(raw.Length + 1);
            for (int i = 0; i < raw.Length; i++)
            {
                char ch = raw[i];
                bool ok = (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                          ch == '_' || (ch >= '0' && ch <= '9' && i > 0);
                sb.Append(ok ? ch : '_');
            }
            if (sb.Length > 0 && sb[0] >= '0' && sb[0] <= '9')
                sb.Insert(0, '_');
            string ident = sb.ToString();
            if (Keywords.Contains(ident)) ident = "@" + ident;
            return ident;
        }

        /// <summary>
        /// Builds the full .cs source for a module. moduleName is the asset
        /// stem (e.g. "Patrol"), className the desired class (e.g. "PatrolAI"),
        /// resourcePath the Resources path of the .fsmb (e.g. "MyFSM/Patrol").
        /// </summary>
        public static string GenerateSource(FsmbModule module, string moduleName,
                                            string className, string resourcePath)
        {
            string cls = SanitizeIdentifier(className);
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> myFSM class generator — do not edit by hand.");
            sb.AppendLine("// Module: " + moduleName + " (v" + module.Major + "." +
                          module.Minor + ", " + module.States.Count + " states).");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using MyFSM.Unity;");
            sb.AppendLine();
            sb.AppendLine("public sealed class " + cls + " : AIInstance");
            sb.AppendLine("{");
            sb.AppendLine("    public const string AssetResourcePath = \"" + resourcePath + "\";");
            sb.AppendLine("    protected override string ModuleResourcePath");
            sb.AppendLine("    {");
            sb.AppendLine("        get { return AssetResourcePath; }");
            sb.AppendLine("    }");
            sb.AppendLine("    protected override string GeneratedModuleName");
            sb.AppendLine("    {");
            sb.AppendLine("        get { return \"" + moduleName + "\"; }");
            sb.AppendLine("    }");
            sb.AppendLine();
            for (int i = 0; i < module.States.Count; i++)
            {
                sb.AppendLine("    public const string State_" +
                              SanitizeIdentifier(module.States[i].Name) + " = \"" +
                              module.States[i].Name + "\";");
            }
            if (module.Runtime.Count > 0) sb.AppendLine();
            for (int i = 0; i < module.Runtime.Count; i++)
            {
                sb.AppendLine("    public const int Slot_" +
                              SanitizeIdentifier(module.Runtime[i].Name) + " = " +
                              module.Runtime[i].BindingSlot + "; // " +
                              DslTypes.NameOf(module.Runtime[i].Tag));
            }
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
