#!/usr/bin/env python3
"""Emits the myFSM generated-class source for a compiled module.

This is a faithful mirror of ClassGenerator.GenerateSource(module, bytes, ...)
in Runtime/Unity/ClassGenerator.cs: same header, same State_/Slot_ constants,
same per-slot comments (auto-bound / AMBIGUOUS / value / unknown), the same
OnBindingsManual() hook, and the same base64 blob at the bottom wrapped in
96-character lines. It exists because the test modules in this folder are
pre-compiled here, on the command line, where the C# generator cannot run.

Input is the module's disassembly (fsmc -d), which names the states and the
runtime variables with their binding slots and DSL types, plus the .fsmb bytes
to embed.

    python3 gen_class.py <module.fsmd> <module.fsmb> <ModuleName> <ClassName> [outdir]

writes <ClassName>.cs into [outdir] (default: next to the .fsmd). Hand-written binding code does not go
in there: it implements partial void OnBindingsManual() in a separate file
(<ClassName>.Manual.cs), exactly like a Unity-generated class.
"""
import base64
import os
import re
import sys

KEYWORDS = {
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
    "checked", "class", "const", "continue", "decimal", "default", "delegate",
    "do", "double", "else", "enum", "event", "explicit", "extern", "false",
    "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
    "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
    "new", "null", "object", "operator", "out", "override", "params", "private",
    "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
    "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
    "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
    "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
}

# DslTypes (Runtime/Core/FsmbFormat.cs): the types carried as object handles.
HANDLE_TYPES = {
    "Object2D", "Object3D", "Transform2D", "Transform3D", "Camera2D", "Camera3D",
    "Sprite2D", "Sprite3D", "AnimationController2D", "AnimationController3D",
    "PhysicsObject2D", "PhysicsObject3D", "NavMeshAgent",
}


def sanitize(raw):
    """ClassGenerator.SanitizeIdentifier, mirrored."""
    if not raw:
        return "_"
    out = []
    for i, ch in enumerate(raw):
        ok = ch.isalpha() or ch == "_" or (ch.isdigit() and i > 0)
        out.append(ch if ok else "_")
    ident = "".join(out)
    if ident and ident[0].isdigit():
        ident = "_" + ident
    if ident in KEYWORDS:
        ident = "@" + ident
    return ident


def maker_for_value_type(type_name):
    """ClassGenerator.MakerForValueType, mirrored."""
    return {
        "int": "MakeInt(0)",
        "float": "MakeFloat(0f)",
        "double": "MakeDouble(0.0)",
        "bool": "MakeBool(false)",
        "string": 'MakeString("")',
        "Vector2": "MakeVec2(0f, 0f)",
        "Vector3": "MakeVec3(0f, 0f, 0f)",
        "Quaternion": "MakeQuat(0f, 0f, 0f, 1f)",
    }.get(type_name, "/* see FsmValue makers */")


def parse_disassembly(path):
    """Pulls the module version, states and runtime variables out of a .fsmd."""
    text = open(path, encoding="utf-8").read()
    version = re.search(r"format\s+fsmb v(\d+)\.(\d+)", text)
    states, runtime = [], []
    section = None
    for line in text.splitlines():
        head = re.match(r"\s*SECTION \[(\d+)\] (\w+)", line)
        if head:
            section = head.group(2)
            continue
        row = re.match(r"\s*#(\d+)\s+(\S+)\s+(.*)$", line)
        if not row or section is None:
            continue
        name, rest = row.group(2), row.group(3)
        if section == "STATES":
            states.append(name)
        elif section == "RUNTIME":
            slot = re.search(r"slot\s+(\d+)", rest)
            type_name = rest.split()[0] if rest.split() else ""
            if slot:
                runtime.append((name, type_name, int(slot.group(1))))
    if not version:
        raise SystemExit("gen_class: could not read the module version from " + path)
    return int(version.group(1)), int(version.group(2)), states, runtime


def generate(module_name, class_name, module_bytes, major, minor, states, runtime):
    """ClassGenerator.GenerateSource(module, bytes, ...), mirrored line for line."""
    cls = sanitize(class_name)
    out = []
    add = out.append
    add("// <auto-generated> myFSM class generator — do not edit by hand.")
    add("// Module: %s (v%d.%d, %d states)." % (module_name, major, minor, len(states)))
    add("// Self-contained: attach this component and press Play - the module it")
    add("// runs is compiled in at the bottom of this file. Nothing to assign.")
    add("using UnityEngine;")
    add("using MyFSM.Unity;")
    add("")
    add("public sealed partial class %s : AIInstance" % cls)
    add("{")
    add("    protected override string GeneratedModuleName")
    add("    {")
    add('        get { return "%s"; }' % module_name)
    add("    }")
    add("")
    for name in states:
        add('    public const string State_%s = "%s";' % (sanitize(name), name))
    if runtime:
        add("")
    per_tag = {}
    for name, type_name, slot in runtime:
        per_tag[type_name] = per_tag.get(type_name, 0) + 1
    for name, type_name, slot in runtime:
        add("    public const int Slot_%s = %d; // %s" % (sanitize(name), slot, type_name))
    add("")
    add("    // Runtime-variable overrides: the base auto-binds every UNIQUE")
    add("    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,")
    add("    // Transform2D/3D -> transform, component types -> GetComponent).")
    add("    // Edits here are lost on recompile - durable overrides belong in a")
    add("    // hand-written partial file implementing OnBindingsManual().")
    add("    protected override void OnBindingsRequired()")
    add("    {")
    add("        base.OnBindingsRequired();")
    for name, type_name, slot in runtime:
        slot_const = "Slot_" + sanitize(name)
        is_handle = type_name in HANDLE_TYPES
        if is_handle and per_tag[type_name] == 1:
            add("        // %s (%s): auto-bound (unique type) - override with Bind(%s, ...) if needed."
                % (slot_const, type_name, slot_const))
        elif is_handle:
            add("        // %s (%s): AMBIGUOUS (%dx) - Bind(%s, /* GameObject/Component */);"
                % (slot_const, type_name, per_tag[type_name], slot_const))
        elif type_name in ("int", "float", "double", "bool", "string",
                           "Vector2", "Vector3", "Quaternion"):
            add("        // %s (%s): value - SetBoundValue(%s, FsmValue.%s);"
                % (slot_const, type_name, slot_const, maker_for_value_type(type_name)))
        else:
            add("        // %s (%s): unknown type - bind manually." % (slot_const, type_name))
    add("        OnBindingsManual();")
    add("    }")
    add("")
    add("    partial void OnBindingsManual();")
    blob = base64.b64encode(module_bytes).decode("ascii")
    add("")
    add("    // ================================================================")
    add("    // THIS AI'S BRAIN - %d bytes of compiled module." % len(module_bytes))
    add("    // It is the .fsmb, base64-encoded so it can live in a C# file. The")
    add("    // base class reads it; nothing here needs assigning or editing.")
    add("    // ================================================================")
    add("    private static readonly byte[] ModuleData =")
    add("        System.Convert.FromBase64String(")
    for i in range(0, len(blob), 96):
        chunk = blob[i:i + 96]
        line = '            "%s"' % chunk
        if i + 96 < len(blob):
            line += " +"
        add(line)
    add("        );")
    add("    protected override byte[] EmbeddedModule")
    add("    {")
    add("        get { return ModuleData; }")
    add("    }")
    add("}")
    return "\n".join(out) + "\n"


def main(argv):
    if len(argv) not in (5, 6):
        raise SystemExit(__doc__.strip().splitlines()[-1])
    fsmd, fsmb, module_name, class_name = argv[1:5]
    major, minor, states, runtime = parse_disassembly(fsmd)
    module_bytes = open(fsmb, "rb").read()
    src = generate(module_name, class_name, module_bytes, major, minor, states, runtime)
    out_dir = argv[5] if len(argv) == 6 else os.path.dirname(os.path.abspath(fsmd))
    out_path = os.path.join(out_dir, class_name + ".cs")
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write(src)
    print("wrote %s (%d bytes of module, %d states, %d runtime vars)"
          % (out_path, len(module_bytes), len(states), len(runtime)))


if __name__ == "__main__":
    main(sys.argv)
