// <auto-generated> myFSM class generator — do not edit by hand.
// Module: Chaser (v0.5, 1 states).
// Self-contained: attach this component and press Play - the module it
// runs is compiled in at the bottom of this file. Nothing to assign.
using UnityEngine;
using MyFSM.Unity;

public sealed partial class ChaserAI : AIInstance
{
    protected override string GeneratedModuleName
    {
        get { return "Chaser"; }
    }

    public const string State_Chase = "Chase";

    public const int Slot_self = 0; // Object3D
    public const int Slot_player = 1; // Object3D

    // Runtime-variable overrides: the base auto-binds every UNIQUE
    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,
    // Transform2D/3D -> transform, component types -> GetComponent).
    // Edits here are lost on recompile - durable overrides belong in a
    // hand-written partial file implementing OnBindingsManual().
    protected override void OnBindingsRequired()
    {
        base.OnBindingsRequired();
        // Slot_self (Object3D): AMBIGUOUS (2x) - Bind(Slot_self, /* GameObject/Component */);
        // Slot_player (Object3D): AMBIGUOUS (2x) - Bind(Slot_player, /* GameObject/Component */);
        OnBindingsManual();
    }

    partial void OnBindingsManual();

    // ================================================================
    // THIS AI'S BRAIN - 232 bytes of compiled module.
    // It is the .fsmb, base64-encoded so it can live in a C# file. The
    // base class reads it; nothing here needs assigning or editing.
    // ================================================================
    private static readonly byte[] ModuleData =
        System.Convert.FromBase64String(
            "RE1TRgAABQAkAAAAOQAAAFkAAABZAAAAaAAAAHoAAADaAAAAAAAAIAIAAMBACgBjaGFzZVNwZWVkAAAAQCEAAAAABABzZWxm" +
            "DwAAQCEBAAAABgBwbGF5ZXIBAAAAAAAAwAUAQ2hhc2UEAACAAgABASEAAMADAQQAAIABAgAMAADAUgAAwAECAgAXAADAGgAA" +
            "wAcAAAgBACEAAMAQAAAmBgMzAADAOgAAwEsAAMAjAAAAAABAEAAAAAEBRAAAwCMAAA8AAEAjAAAAAAAgAwEAWQAAwBEAAAQA" +
            "AIABAAAABAAAgAEABAAAgA=="
        );
    protected override byte[] EmbeddedModule
    {
        get { return ModuleData; }
    }
}
