// <auto-generated> myFSM class generator — do not edit by hand.
// Module: ZoneBridge (v0.5, 3 states).
// Self-contained: attach this component and press Play - the module it
// runs is compiled in at the bottom of this file. Nothing to assign.
using UnityEngine;
using MyFSM.Unity;

public sealed partial class ZoneBridgeAI : AIInstance
{
    protected override string GeneratedModuleName
    {
        get { return "ZoneBridge"; }
    }

    public const string State_AtHome = "AtHome";
    public const string State_Above10 = "Above10";
    public const string State_Above40 = "Above40";

    public const int Slot_self = 0; // Object3D
    public const int Slot_marker = 1; // Object3D
    public const int Slot_home = 2; // Vector3
    public const int Slot_zone = 3; // int

    // Runtime-variable overrides: the base auto-binds every UNIQUE
    // handle slot to this GameObject at boot (Object2D/3D -> gameObject,
    // Transform2D/3D -> transform, component types -> GetComponent).
    // Edits here are lost on recompile - durable overrides belong in a
    // hand-written partial file implementing OnBindingsManual().
    protected override void OnBindingsRequired()
    {
        base.OnBindingsRequired();
        // Slot_self (Object3D): AMBIGUOUS (2x) - Bind(Slot_self, /* GameObject/Component */);
        // Slot_marker (Object3D): AMBIGUOUS (2x) - Bind(Slot_marker, /* GameObject/Component */);
        // Slot_home (Vector3): value - SetBoundValue(Slot_home, FsmValue.MakeVec3(0f, 0f, 0f));
        // Slot_zone (int): value - SetBoundValue(Slot_zone, FsmValue.MakeInt(0));
        OnBindingsManual();
    }

    partial void OnBindingsManual();

    // ================================================================
    // THIS AI'S BRAIN - 950 bytes of compiled module.
    // It is the .fsmb, base64-encoded so it can live in a C# file. The
    // base class reads it; nothing here needs assigning or editing.
    // ================================================================
    private static readonly byte[] ModuleData =
        System.Convert.FromBase64String(
            "RE1TRgAABQAkAAAAVgAAAJQAAACUAAAAvgAAACQBAACAAwAAAAAAIBEAAAAAAAAgQQAAAAAGAGxpZnQxMBkAACARAAAAAAAA" +
            "IEIAAAAABgBsaWZ0NDAAAABAIQAAAAAEAHNlbGYPAABAIQEAAAAGAG1hcmtlciAAAEARAgAAAAQAaG9tZS8AAEABAwAAAAQA" +
            "em9uZQMAAAAAAADABgBBdEhvbWWcAADABwBBYm92ZTEwfAEAwAcAQWJvdmU0MAQAAIAEAAEBIgAAwAEBPgAAwAMBEAAAgAMB" +
            "BAAAgBAAAIAFAAEBvgAAwAEB7QAAwAMBHQAAgAMBBAAAgAMBEAAAgB0AAIAFAAEBngEAwAEBzQEAwAMBBAAAgAMBEAAAgAMB" +
            "HQAAgAECAAwAAMBdAADAAQICABcAAMBaAADABwIAIgAAwD4AAMAQAAAFAQIwAADANwAAwCMAAAAAAEAjAAAgAABAEAAABQEC" +
            "TAAAwFMAAMAjAAAPAABAIwAAIAAAQAgAAAMCAGgAAMCVAADABAEAjgAAwHMAAMAgAAANfwAAwIYAAMAjAAAvAABAIgAAAQoA" +
            "AAARAAAQAACAEQAABAAAgAECAKgAAMAMAQDAAAICALMAAMAJAQDABwIAvgAAwO0AAMAQAAAFAQLMAADA0wAAwCMAAAAAAEAg" +
            "AAAB3wAAwOYAAMAjAAAgAABAIwAAAAAAIBAAAAUBAvsAAMACAQDAIwAADwAAQCMAACAAAEAIAAADAwAbAQDASAEAwHUBAMAE" +
            "AQBBAQDAJgEAwCAAAA0yAQDAOQEAwCMAAC8AAEAiAAABFAAAABEAAB0AAIAEAQBuAQDAUwEAwCAAAA5fAQDAZgEAwCMAAC8A" +
            "AEAiAAABCgAAABEAAAQAAIARAAAQAACAAQIAiAEAwOwBAMAAAgIAkwEAwOkBAMAHAgCeAQDAzQEAwBAAAAUBAqwBAMCzAQDA" +
            "IwAAAAAAQCAAAAG/AQDAxgEAwCMAACAAAEAjAAAZAAAgEAAABQEC2wEAwOIBAMAjAAAPAABAIwAAIAAAQAgAAAMDAPsBAMAo" +
            "AgDAVQIAwAQBACECAMAGAgDAIAAADhICAMAZAgDAIwAALwAAQCIAAAEKAAAAEQAABAAAgAQBAE4CAMAzAgDAIAAADj8CAMBG" +
            "AgDAIwAALwAAQCIAAAEUAAAAEQAAEAAAgBEAAB0AAIADAAAABAAAgAIAEAAAgAQAAIAQAACAAwAdAACABAAAgBAAAIAdAACA" +
            "AwAEAACAEAAAgB0AAIA="
        );
    protected override byte[] EmbeddedModule
    {
        get { return ModuleData; }
    }
}
